apiVersion: v1
kind: Service
metadata:
  name: my-react-app-service
  namespace: my-react-app
spec:
  selector:
    app: my-react-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 800
      targetPort: 8080
  loadBalancerIP: 10.0.0.11
